{
 "title": "Let's Encrypt",
 "tags": [ "certs" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Until Expiration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({service_name=\"pi-certs-1\"} |= `/etc/letsencrypt/live/getorganize.app/fullchain.pem expires on` | pattern `<_> expires on <expiration> <_>` | label_format expiration=`{{ .expiration | toDateInZone \"2006-01-02\" \"UTC\" | unixEpoch }}` | label_format seconds_until_expiration=`{{now | unixEpoch | sub .expiration }}` | unwrap seconds_until_expiration [$__auto]) / (60*60*24)"
    }
   ]
  },
  {
   "title": "Expiration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({service_name=\"pi-certs-1\"} |= `/etc/letsencrypt/live/getorganize.app/fullchain.pem expires on` | pattern `<_> expires on <expiration> <_>` | label_format expiration=`{{ .expiration | toDateInZone \"2006-01-02\" \"UTC\" | unixEpoch }}` | unwrap expiration [$__auto]) * 1000"
    }
   ]
  },
  {
   "title": "Time Since Last Renewal Attempt",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({service_name=\"pi-certs-1\"} |= `/etc/letsencrypt/live/getorganize.app/fullchain.pem expires on` | label_format ts=`{{__timestamp__ | unixEpoch}}` | label_format seconds_since_attempt=`{{sub (now | unixEpoch) .ts }}` | unwrap seconds_since_attempt [$__auto]) / (60*60)"
    }
   ]
  }
 ]
}