{
 "title": "Loki Metrics Dashboard",
 "description": "Loki Metrics Dashboard",
 "tags": [ "loki" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "jobs",
    "label": "Job",
    "query": {
     "query": "label_values(loki_build_info,job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "up{job=~\"$jobs\"}"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "up{job=~\"$jobs\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Loki General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_build_info{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Faktor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_distributor_replication_factor{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "The configured replication factor"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_info{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"$jobs\",instance=\"$host:$instance\"})",
     "legendFormat": "Number of goroutines that currently exist"
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"$jobs\",instance=\"$host:$instance\"})",
     "legendFormat": "Number of OS threads created"
    }
   ]
  },
  {
   "title": "Distributor Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Internal Log Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_internal_log_messages_total{job=\"$jobs\",instance=\"$host:$instance\"})"
    }
   ]
  },
  {
   "title": "Distributor Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_panic_total{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "The total number of panics triggered"
    }
   ]
  },
  {
   "title": "Features Currently Set",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deprecated_flags_inuse_total{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Deprecated"
    },
    {
     "expr": "loki_experimental_features_in_use_total{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Experimental"
    }
   ]
  },
  {
   "title": "Ingester Chunk Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(loki_ingester_chunks_stored_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant) ",
     "legendFormat": "Store / {{ tenant }}"
    }
   ]
  },
  {
   "title": "Store Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_series_total{job=\"$jobs\",instance=\"$host:$instance\"}) by(status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Store Chunks Downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_chunks_downloaded_total{job=\"$jobs\",instance=\"$host:$instance\"}) by(status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Index Chunks Downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_index_chunk_refs_total{job=\"$jobs\",instance=\"$host:$instance\"}) by(status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Chunk Storage Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_ingester_chunk_stored_bytes_total",
     "legendFormat": "Chunk Size"
    }
   ]
  },
  {
   "title": "Ingester Chunks In Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_ingester_memory_chunks{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Chunks in memory"
    }
   ]
  },
  {
   "title": "Ingester Streams in Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_streams{job=\"$jobs\",instance=\"$host:$instance\"}) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Ingester Chunks Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Ingester Chunk Compression",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Compression Ratio"
    }
   ]
  },
  {
   "title": "Store Operations Fetched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_fetched_chunks_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (user)",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Store Volume Fetched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_fetched_chunk_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Store Operations Stored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_stored_chunks_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (user)",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Store Volume Stored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_stored_chunk_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Ingester Chunk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Chunk Size"
    }
   ]
  },
  {
   "title": "Ingester Stream Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_streams_created_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "Create / {{ tenant }}"
    },
    {
     "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "Delete / {{ tenant }}"
    }
   ]
  },
  { "title": "Loki API / Connections Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Loki API - Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,method,route,status_code))",
     "legendFormat": "{{ method }} / {{ route }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki API - Request Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_inflight_requests{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (method, route)",
     "legendFormat": "{{ method }} / {{ route }}"
    }
   ]
  },
  {
   "title": "Loki API - Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_response_message_bytes_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,method,route))",
     "legendFormat": "{{ method }} / {{ route }}"
    }
   ]
  },
  {
   "title": "Loki API - Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_message_bytes_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,method,route))",
     "legendFormat": "{{ method }} / {{ route }}"
    }
   ]
  },
  {
   "title": "Loki - TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_tcp_connections{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  { "title": "Loki Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Loki Cache - Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_cache_hits{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Cache - Fetched Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_cache_fetched_keys{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Cache - Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_cache_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,name,method))",
     "legendFormat": "{{ name }} / {{ method }}"
    }
   ]
  },
  {
   "title": "Loki Cache - Value Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,name,method))",
     "legendFormat": "{{ name }} / {{ method }}"
    }
   ]
  },
  { "title": "Loki Distributor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Loki Distributor - Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Distributor - Received Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Distributor - Batch Appents Sent To Ingester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_ingester_appends_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(ingester)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki Index Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Loki Index - Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_index_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,component,operation,status_code))",
     "legendFormat": "{{ component }} / {{ operation }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki Index - Chunks Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_index_chunk_refs_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Loki KV - Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_kv_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,kv_name,operation,role,status_code,type))",
     "legendFormat": "{{ kv_name }} / {{ type }} / {{ operation }} / {{ status_code }}"
    }
   ]
  },
  { "title": "Loki Ingester Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Loki Ingester - Client Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_client_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,operation,status_code))",
     "legendFormat": "{{ operation }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Chunk creations "
    },
    {
     "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Chunk flushes / {{ reason }}"
    },
    {
     "expr": "sum(rate(loki_ingester_chunks_stored_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant) ",
     "legendFormat": "Chunks stored / {{ tenant }}"
    }
   ]
  },
  {
   "title": "Loki Ingester - Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_checkpoint_creations_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Checkpoint creations "
    },
    {
     "expr": "rate(loki_ingester_checkpoint_creations_failed_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Checkpoint creation failures"
    },
    {
     "expr": "rate(loki_ingester_checkpoint_deletions_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Checkpoint deletions"
    },
    {
     "expr": "rate(loki_ingester_checkpoint_deletions_failed_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Checkpoint deletion failures"
    }
   ]
  },
  {
   "title": "Loki Ingester - Checkpoints Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_checkpoint_logged_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Bytes written to disk for checkpointing"
    }
   ]
  },
  {
   "title": "Loki Ingester - Checkpoint Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_ingester_checkpoint_duration_seconds{job=\"$jobs\",instance=\"$host:$instance\",quantile=\"0.99\"}",
     "legendFormat": "Time taken to create a checkpoint (0.99 quantile)"
    },
    {
     "expr": "loki_ingester_checkpoint_duration_seconds{job=\"$jobs\",instance=\"$host:$instance\",quantile=\"0.9\"}",
     "legendFormat": "Time taken to create a checkpoint (0.9 quantile)"
    },
    {
     "expr": "loki_ingester_checkpoint_duration_seconds{job=\"$jobs\",instance=\"$host:$instance\",quantile=\"0.5\"}",
     "legendFormat": "Time taken to create a checkpoint (0.5 quantile)"
    }
   ]
  },
  {
   "title": "Loki Ingester - Blocks Per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Blocks per Chunk"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Compression Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Compression ratio of chunks (when stored)"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunks In Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_ingester_memory_chunks{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Chunks in memory"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Distribution of stored chunk sizes (when stored)"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Distribution of chunk ages (when stored)"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_utilization_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Distribution of stored chunk utilization (when stored)"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Stored Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "Bytes stored in chunks / {{ tenant }}"
    }
   ]
  },
  {
   "title": "Loki Ingester - Samples Per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_samples_per_chunk_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Samples per chunk"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Bounds (Hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_bounds_hours_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Distribution of chunk end-start durations"
    }
   ]
  },
  {
   "title": "Loki Ingester - Chunk Encoding Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Distribution of chunk encode times"
    }
   ]
  },
  {
   "title": "Loki Ingester - Lines Per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Distribution of stored lines per chunk (when stored)"
    }
   ]
  },
  {
   "title": "Loki Ingester - Stream Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_streams_created_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "Stream creations / {{ tenant }}"
    },
    {
     "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "Stream deletetions / {{ tenant }}"
    }
   ]
  },
  {
   "title": "Loki Ingester - Streams In Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_streams{job=\"$jobs\",instance=\"$host:$instance\"}) by (tenant)",
     "legendFormat": "Streams in memory / {{ tenant }}"
    }
   ]
  },
  {
   "title": "Loki Ingester - WAL Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_wal_records_logged_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "WAL records logged"
    },
    {
     "expr": "rate(loki_ingester_wal_duplicate_entries_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Discarded entries during WAL replay due to existing in checkpoints"
    },
    {
     "expr": "rate(loki_ingester_wal_disk_full_failures_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "WAL write failures due to full disk"
    },
    {
     "expr": "sum(rate(loki_ingester_wal_discarded_samples_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (reason)",
     "legendFormat": "WAL segment entries discarded during replay / {{ reason }}"
    }
   ]
  },
  {
   "title": "Loki Ingester - WAL Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "loki_ingester_wal_bytes_in_use{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Currently in use by the WAL recovery process"
    },
    {
     "expr": "rate(loki_ingester_wal_logged_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Written to disk for WAL records"
    },
    {
     "expr": "sum(rate(loki_ingester_wal_discarded_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (reason)",
     "legendFormat": "WAL segment bytes discarded during replay / {{ reason }}"
    },
    {
     "expr": "sum(rate(loki_ingester_wal_discarded_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Recovered from the WAL"
    }
   ]
  },
  {
   "title": "Loki Ingester - WAL Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_wal_recovered_entries_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Entries recovered from the WAL"
    },
    {
     "expr": "rate(loki_ingester_wal_recovered_chunks_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Chunks recovered from the WAL checkpoints"
    },
    {
     "expr": "rate(loki_ingester_wal_recovered_streams_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Streams recovered from the WAL"
    }
   ]
  },
  {
   "title": "Loki Ingester - WAL Replay Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_ingester_wal_replay_active{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "WAL is replaying"
    },
    {
     "expr": "loki_ingester_wal_replay_flushing{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "WAL replay in flushing phase due to backpressure"
    }
   ]
  },
  { "title": "Loki Line Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "Loki - Internal Log Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Loki Line - Log Flushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_log_flushes_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Log flushes - line-buffered logger"
    }
   ]
  },
  {
   "title": "Loki Line - Line Size Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "targets": [
    {
     "expr": "rate(loki_bytes_per_line_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Line - Line Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_bytes_per_line_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Number of bytes per line"
    }
   ]
  },
  { "title": "Loki LogQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Loki LogQL - Lines Received From Ingester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(loki_logql_querystats_ingester_sent_lines_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Lines"
    }
   ]
  },
  {
   "title": "Loki LogQL - Duplicates Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(loki_logql_querystats_duplicates_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Lines"
    }
   ]
  },
  {
   "title": "Loki LogQL - Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(logql_query_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,query_type))",
     "legendFormat": "{{ query_type }}"
    }
   ]
  },
  {
   "title": "Loki LogQL - Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,type,status_code))",
     "legendFormat": "{{ type }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki LogQL - Query Volume Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,type,status_code))",
     "legendFormat": "{{ type }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki LogQL - Downloaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_logql_querystats_downloaded_chunk_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by(type,status_code)",
     "legendFormat": "{{ type }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki LogQL - Chunk Download Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_chunk_download_latency_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,type,status_code))",
     "legendFormat": "{{ type }} / {{ status_code }}"
    }
   ]
  },
  { "title": "Loki Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "Loki Querier - Frontend Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_querier_query_frontend_request_duration_seconds_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,operation,status_code))",
     "legendFormat": "{{ operation }} / {{ status_code }}"
    }
   ]
  },
  {
   "title": "Loki Querier - Frontend Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(loki_query_frontend_log_result_cache_hit_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Cache hits for the frontend cache"
    },
    {
     "expr": "rate(loki_query_frontend_log_result_cache_miss_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Cache misses for the frontend cache"
    }
   ]
  },
  {
   "title": "Loki Querier - Frontend Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_partitions_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Time-based partitions (sub-requests) per request"
    }
   ]
  },
  {
   "title": "Loki Querier - Frontend Shard Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_shard_factor_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,mapper))",
     "legendFormat": "Downstream queries per request / {{ mapper }}"
    }
   ]
  },
  {
   "title": "Loki Querier - Frontend Shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_query_frontend_sharding_parsed_queries_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,mapper,type)",
     "legendFormat": "Parsed queries by evaluation type / {{ mapper }} / {{ type }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_shards_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,mapper,type))",
     "legendFormat": "Downstream queries by expression type / {{ mapper }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Loki Querier - Index Cache Clients / Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_querier_query_frontend_clients{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Clients connected to query-frontend"
    },
    {
     "expr": "loki_querier_tail_active{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Active tailers"
    },
    {
     "expr": "loki_querier_tail_active_streams{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Active streams being tailed"
    },
    {
     "expr": "loki_querier_worker_concurrency{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Concurrent querier workers"
    },
    {
     "expr": "loki_querier_worker_inflight_queries{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Queries being processed by the querier workers"
    }
   ]
  },
  {
   "title": "Loki Querier - Index Cache Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(loki_querier_index_cache_gets_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Gets for the index cache"
    },
    {
     "expr": "rate(loki_querier_index_cache_puts_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Puts for the index cache"
    },
    {
     "expr": "rate(loki_querier_index_cache_hits_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Cache hits for the index cache"
    },
    {
     "expr": "rate(loki_querier_index_cache_corruptions_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Cache corruptions for the index cache"
    },
    {
     "expr": "rate(loki_querier_index_cache_encode_errors_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Errors for the index cache while encoding the body"
    }
   ]
  },
  {
   "title": "Loki Query Cache - Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(querier_cache_entries{job=\"$jobs\",instance=\"$host:$instance\"}) by (cache)",
     "legendFormat": "Cache Entries / {{ cache }}"
    }
   ]
  },
  {
   "title": "Loki Query Cache - Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(querier_cache_added_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (cache)",
     "legendFormat": "Entries added to the cache / {{ cache }}"
    },
    {
     "expr": "sum(rate(querier_cache_added_new_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (cache)",
     "legendFormat": "New entries added to the cache / {{ cache }}"
    },
    {
     "expr": "sum(rate(querier_cache_evicted_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (cache,reason)",
     "legendFormat": "Entries evicted from the cache / {{ cache }} / {{ reason }}"
    },
    {
     "expr": "sum(rate(querier_cache_gets_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (cache)",
     "legendFormat": "Get calls to the cache / {{ cache }}"
    },
    {
     "expr": "sum(rate(querier_cache_misses_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (cache)",
     "legendFormat": "Missed calls to the cache / {{ cache }}"
    }
   ]
  },
  {
   "title": "Loki Query Cache - Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(querier_cache_memory_bytes{job=\"$jobs\",instance=\"$host:$instance\"}) by (cache)",
     "legendFormat": "Current cache size / {{ cache }}"
    }
   ]
  },
  { "title": "Loki Ring Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 272 } },
  {
   "title": "Loki Ring - Heartbeats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(ring_member_heartbeats_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (name)",
     "legendFormat": "Heartbeats sent / {{ name }}"
    }
   ]
  },
  {
   "title": "Loki Ring - Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ring_member_tokens_owned{job=\"$jobs\",instance=\"$host:$instance\"}) by (name)",
     "legendFormat": "Tokens owned / {{ name }}"
    },
    {
     "expr": "sum(ring_member_tokens_to_own{job=\"$jobs\",instance=\"$host:$instance\"}) by (name)",
     "legendFormat": "Tokens to be owned / {{ name }}"
    }
   ]
  },
  { "title": "Loki Store Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 281 } },
  {
   "title": "Loki Store - Series Referenced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_store_series_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Loki Store - Chunks Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_store_chunks_downloaded_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Loki Store - Chunk Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_store_chunks_per_batch_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le,status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Loki Store - Chunk Fetcher Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(loki_chunk_fetcher_cache_dequeued_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Dequeue from buffer"
    },
    {
     "expr": "rate(loki_chunk_fetcher_cache_enqueued_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Enqueue to buffer"
    },
    {
     "expr": "rate(loki_chunk_fetcher_cache_skipped_buffer_full_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Skipped due to buffer full"
    }
   ]
  },
  {
   "title": "Loki Store - Fetched / Stored Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_fetched_chunks_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (user)",
     "legendFormat": "Fetched / {{ user }}"
    },
    {
     "expr": "sum(rate(loki_chunk_store_stored_chunks_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (user)",
     "legendFormat": "Stored / {{ user }}"
    }
   ]
  },
  {
   "title": "Loki Store - Fetched / Stored Chunk Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_fetched_chunk_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Fetched / {{ user }}"
    },
    {
     "expr": "rate(loki_chunk_store_stored_chunk_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Stored / {{ user }}"
    }
   ]
  },
  {
   "title": "Loki Store - Chunks Per Query Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_chunks_per_query_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Chunks Per Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_chunks_per_query_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Index Entries Per Chunk Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 314 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_index_entries_per_chunk_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Index Entries Per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_index_entries_per_chunk_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Index Lookups Per Query Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 322 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_index_lookups_per_query_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Index Lookups Per Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 322 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_index_lookups_per_query_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Series (Pre Intersection) Per Chunk Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 330 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_series_pre_intersection_per_query_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Series (Pre Intersection) Per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 330 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_series_pre_intersection_per_query_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Series (Post Intersection) Per Chunk Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 338 },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_series_post_intersection_per_query_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki Store - Series (Post Intersection) Per Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 338 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_series_post_intersection_per_query_bucket{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Go General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 346 } },
  {
   "title": "Go - Goroutines / Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Go - Goroutines Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 347 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_sched_latencies_seconds_sum{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])/rate(go_sched_latencies_seconds_count{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Average Goroutine latency"
    }
   ]
  },
  {
   "title": "Go - Goroutines Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 355 },
   "targets": [
    {
     "expr": "rate(go_sched_latencies_seconds_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Go Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 363 } },
  {
   "title": "Go - Memory Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 364 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_classes_heap_free_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Free memory"
    },
    {
     "expr": "go_memory_classes_heap_objects_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Allocated objects memory"
    },
    {
     "expr": "go_memory_classes_heap_released_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Released memory"
    },
    {
     "expr": "go_memory_classes_heap_stacks_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Stack reserved memory"
    },
    {
     "expr": "go_memory_classes_heap_unused_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Reserved unused memory"
    }
   ]
  },
  {
   "title": "Go - Memory Metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 364 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_classes_metadata_mcache_free_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Free mcache memory"
    },
    {
     "expr": "go_memory_classes_metadata_mcache_inuse_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Used mcache memory"
    },
    {
     "expr": "go_memory_classes_metadata_mspan_free_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Free mspan memory"
    },
    {
     "expr": "go_memory_classes_metadata_mspan_inuse_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Used mspan memory"
    },
    {
     "expr": "go_memory_classes_metadata_other_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Used other metadata memory"
    },
    {
     "expr": "go_memory_classes_other_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Used other memory"
    },
    {
     "expr": "go_memory_classes_profiling_buckets_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Used profiling bucket memory"
    }
   ]
  },
  {
   "title": "Go - Heap Object Allocation / Free Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 372 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_gc_heap_allocs_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])/rate(go_gc_heap_allocs_objects_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Average object size allocated to the heap by the application"
    },
    {
     "expr": "rate(go_gc_heap_frees_bytes_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])/rate(go_gc_heap_frees_objects_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Average object size freed from the heap by the GC"
    }
   ]
  },
  {
   "title": "Go - Heap Free Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 372 },
   "targets": [
    {
     "expr": "rate(go_gc_heap_frees_by_size_bytes_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Go - Heap Allocation Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 380 },
   "targets": [
    {
     "expr": "rate(go_gc_heap_allocs_by_size_bytes_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Go GC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 388 } },
  {
   "title": "Go - Garbage Collection Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 389 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Count of all completed GC cycles"
    },
    {
     "expr": "rate(go_gc_cycles_automatic_gc_cycles_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Count of completed GC cycles generated by the Go runtime"
    },
    {
     "expr": "rate(go_gc_cycles_forced_gc_cycles_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Count of completed GC cycles forced by the application."
    }
   ]
  },
  {
   "title": "Go - Garbage Collection Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 389 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])/rate(go_gc_duration_seconds_count{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Average GC cycle pause duration"
    },
    {
     "expr": "rate(go_gc_pauses_seconds_sum{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])/rate(go_gc_pauses_seconds_count{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Average GC cycle halt duration"
    }
   ]
  },
  {
   "title": "Go - Garbage Collection Pauses Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 397 },
   "targets": [
    {
     "expr": "rate(go_gc_pauses_seconds_bucket{job=\"$jobs\", instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 405 } },
  {
   "title": "Process - CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 406 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
     "legendFormat": "Total user and system CPU time spent in seconds"
    }
   ]
  },
  {
   "title": "Process - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 406 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Virtual memory size"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Resident memory size"
    }
   ]
  },
  {
   "title": "Process - File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 414 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Maximum number of open file descriptors"
    },
    {
     "expr": "process_open_fds{job=\"$jobs\",instance=\"$host:$instance\"}",
     "legendFormat": "Number of open file descriptors"
    }
   ]
  }
 ]
}