{
 "title": "Nginx VTS Stats",
 "description": "Show stats from https://github.com/vozlt/nginx-module-vts without exporter.",
 "tags": [
  "prometheus",
  "nginx",
  "nginx-module-vts"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nginx_vts_server_bytes_total, instance)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(nginx_vts_server_bytes_total{instance=~\"$Instance\"}, host)"
    }
   },
   {
    "name": "Upstream",
    "query": {
     "query": "label_values(nginx_vts_upstream_bytes_total{instance=~\"$Instance\"}, upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Writing",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"writing\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"reading\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"waiting\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_requests_total{instance=~\"$Instance\", code!=\"total\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Nginx Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count by (hostname) (nginx_vts_info{instance=~\"$Instance\"}))",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "topk(1, count by (version) (nginx_vts_info{instance=~\"$Instance\"}))",
     "legendFormat": " {{version}}"
    }
   ]
  },
  {
   "title": "Shared Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (shared) (nginx_vts_main_shm_usage_bytes{instance=~\"$Instance\", job=~\"nginx\"})",
     "legendFormat": "{{shared}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(nginx_vts_upstream_request_seconds_total{instance=~\"$Instance\"}[$__rate_interval])\n) /\nsum by (instance) (\n  rate(nginx_vts_upstream_requests_total{instance=~\"$Instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "by server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Requests delta/sec (uptstream)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"$Upstream\", code!=\"total\"} [$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Server Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_cache_total{instance=~\"$Instance\", host=~\"^$Host$\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"^$Host$\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "by upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "timeseries",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\",code!=\"total\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}) by (upstream)",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  }
 ]
}