{
 "title": "Prometheus Metric Counts",
 "description": "Inspect the cardinality of your Prometheus metrics ",
 "tags": [ "prometheus" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "metric", "query": { "query": "label_values(__name__)" } },
   { "name": "job", "label": "job (filter for metrics)", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Total jobs (scrape targets)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count({__name__!=\"\"}) by (job))"
    }
   ]
  },
  {
   "title": "Total metrics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count({__name__!=\"\"}) by (__name__))"
    }
   ]
  },
  {
   "title": "Total series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__!=\"\"})"
    }
   ]
  },
  {
   "title": "Series by job (top 10)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk(10, count({__name__!=\"\"}) by (job))"
    }
   ]
  },
  {
   "title": "Series by metric (top 10)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "topk(10, count({__name__!=\"\",job=~\"$job\"}) by (__name__))"
    }
   ]
  },
  {
   "title": "Cardinality for selected metric by label",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 4 },
   "targets": [
    { "expr": "$metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Series by job (top 100)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(100, count({__name__!=\"\"}) by (job))"
    },
    {
     "expr": "count({__name__!=\"\"})"
    }
   ]
  },
  {
   "title": "Series by metric (top 100)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "topk(100, count({__name__!=\"\",job=~\"$job\"}) by (__name__))"
    },
    {
     "expr": "count({__name__!=\"\"})"
    }
   ]
  }
 ]
}