{
 "title": "Rails",
 "description": "Basic metrics for web applications built with Ruby on Rails.",
 "tags": [
  "rails",
  "puma",
  "active-record"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Rails Service", "query": "api, site" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method) (increase(rails_requests_total{job=~\"$job\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (increase(rails_requests_total{job=~\"$job\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(rails_requests_total{job=~\"$job\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_sum{job=~\"$job\"}[2m]))\n/\nsum(rate(rails_request_duration_seconds_count{job=~\"$job\"}[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum{job=~\"$job\"}[2m]))\n/\nsum(rate(rails_db_runtime_seconds_count{job=~\"$job\"}[2m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum{job=~\"$job\"}[2m]))\n/\nsum(rate(rails_view_runtime_seconds_count{job=~\"$job\"}[2m]))",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{job=~\"$job\"}[2m])) by (controller, action)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails 95% response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rails_request_duration_seconds_bucket{job=~\"$job\"}[2m])) by (le,controller,action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(rails_request_duration_seconds_bucket{job=~\"$job\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(rails_request_duration_seconds_bucket{job=~\"$job\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Active Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Active Record Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "activerecord_connection_pool_busy{job=~\"$job\"}",
     "legendFormat": "busy"
    },
    {
     "expr": "activerecord_connection_pool_dead{job=~\"$job\"}",
     "legendFormat": "dead"
    },
    {
     "expr": "activerecord_connection_pool_idle{job=~\"$job\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Top Queries by Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "topk(5, sum by(kind) (activerecord_queries_total{job=~\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Puma", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Waiting (queued) requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(puma_backlog{job=~\"$job\"})",
     "legendFormat": "Waiting requests"
    }
   ]
  },
  {
   "title": "Thread pool capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(puma_running{job=~\"$job\"} - puma_pool_capacity{job=~\"$job\"})",
     "legendFormat": "Busy threads"
    },
    {
     "expr": "sum(puma_running{job=~\"$job\"})",
     "legendFormat": "Running threads"
    },
    {
     "expr": "sum(puma_max_threads{job=~\"$job\"})",
     "legendFormat": "Maximum threads"
    }
   ]
  },
  {
   "title": "Worker processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(puma_workers{job=~\"$job\"})",
     "legendFormat": "Total worker processes"
    },
    {
     "expr": "sum(puma_workers{job=~\"$job\"} - puma_booted_workers{job=~\"$job\"})",
     "legendFormat": "Booting (not ready) processes"
    },
    {
     "expr": "sum(puma_old_workers{job=~\"$job\"})",
     "legendFormat": "Old worker processes"
    }
   ]
  }
 ]
}