{
 "title": "User Funnel",
 "tags": [ "users" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Page Views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Landing Page Views by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({compose_service=\"web\"} |= `\"uri\": \"/\"` or `\"uri\": \"/cached_pages/index.html\"` | json [$__auto]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(uri) (count_over_time({compose_service=\"web\"} |= `\"status\": \"200\"` | json | label_format uri=`{{ regexReplaceAll \"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\" .uri \":id\" }}` | label_format uri=`{{ regexReplaceAll \"[0-9a-f]{64}\" .uri \"[slug]\" }}` [$__auto]))"
    }
   ]
  },
  { "title": "Store Redirects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Store Redirects by Ref",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (ref) (count_over_time({compose_service=\"web\"} |= `\"uri\": \"/store\"` | regexp `ref=(?P<ref>[\\w\\-]+)` [$__auto]))",
     "legendFormat": "{{ref}}"
    }
   ]
  },
  {
   "title": "Store Redirects by Platform",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (platform) (count_over_time({compose_service=\"web\"} |= `\"uri\": \"/store\"` | regexp `platform=(?P<platform>[\\w\\-]+)` [$__auto]))",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  { "title": "Membership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_n_tup_ins{relname=\"users\"}[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_n_tup_ins{relname=\"connections\"}[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Orgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_n_tup_ins{relname=\"orgs\"}[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  }
 ]
}