# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yabeda-activerecord` gem.
# Please instead update this file by running `bin/tapioca gem yabeda-activerecord`.


# source://yabeda-activerecord//lib/yabeda/active_record/version.rb#3
module Yabeda
  class << self
    # source://yabeda/0.13.1/lib/yabeda.rb#34
    def adapters; end

    # source://yabeda/0.13.1/lib/yabeda.rb#85
    def already_configured?; end

    # source://yabeda/0.13.1/lib/yabeda.rb#52
    def collect!; end

    # source://yabeda/0.13.1/lib/yabeda.rb#39
    def collectors; end

    # source://yabeda/0.13.1/lib/yabeda.rb#43
    def config; end

    # source://yabeda/0.13.1/lib/yabeda.rb#80
    def configurators; end

    # source://yabeda/0.13.1/lib/yabeda.rb#93
    def configure!; end

    # source://yabeda/0.13.1/lib/yabeda.rb#85
    def configured?; end

    # source://yabeda/0.13.1/lib/yabeda.rb#116
    def debug!; end

    # source://forwardable/1.3.3/forwardable.rb#231
    def debug?(*args, **_arg1, &block); end

    # source://yabeda/0.13.1/lib/yabeda.rb#63
    def default_tags; end

    # source://yabeda/0.13.1/lib/yabeda.rb#27
    def groups; end

    # source://yabeda/0.13.1/lib/yabeda.rb#22
    def metrics; end

    # source://yabeda/0.13.1/lib/yabeda.rb#69
    def register_adapter(name, instance); end

    # source://yabeda/0.13.1/lib/yabeda.rb#139
    def reset!; end
  end
end

# ActiveRecord Yabeda plugin to collect metrics for query performance, connection pool stats, etc
#
# source://yabeda-activerecord//lib/yabeda/active_record/version.rb#4
module Yabeda::ActiveRecord; end

# source://yabeda-activerecord//lib/yabeda/active_record.rb#11
class Yabeda::ActiveRecord::Error < ::StandardError; end

# source://yabeda-activerecord//lib/yabeda/active_record.rb#13
Yabeda::ActiveRecord::LONG_RUNNING_QUERY_RUNTIME_BUCKETS = T.let(T.unsafe(nil), Array)

# source://yabeda-activerecord//lib/yabeda/active_record/version.rb#5
Yabeda::ActiveRecord::VERSION = T.let(T.unsafe(nil), String)
