# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yabeda-rails` gem.
# Please instead update this file by running `bin/tapioca gem yabeda-rails`.


# source://yabeda-rails//lib/yabeda/rails/railtie.rb#7
module Yabeda
  class << self
    # source://yabeda/0.13.1/lib/yabeda.rb#34
    def adapters; end

    # source://yabeda/0.13.1/lib/yabeda.rb#85
    def already_configured?; end

    # source://yabeda/0.13.1/lib/yabeda.rb#52
    def collect!; end

    # source://yabeda/0.13.1/lib/yabeda.rb#39
    def collectors; end

    # source://yabeda/0.13.1/lib/yabeda.rb#43
    def config; end

    # source://yabeda/0.13.1/lib/yabeda.rb#80
    def configurators; end

    # source://yabeda/0.13.1/lib/yabeda.rb#93
    def configure!; end

    # source://yabeda/0.13.1/lib/yabeda.rb#85
    def configured?; end

    # source://yabeda/0.13.1/lib/yabeda.rb#116
    def debug!; end

    # source://forwardable/1.3.3/forwardable.rb#231
    def debug?(*args, **_arg1, &block); end

    # source://yabeda/0.13.1/lib/yabeda.rb#63
    def default_tags; end

    # source://yabeda/0.13.1/lib/yabeda.rb#27
    def groups; end

    # source://yabeda/0.13.1/lib/yabeda.rb#22
    def metrics; end

    # source://yabeda/0.13.1/lib/yabeda.rb#69
    def register_adapter(name, instance); end

    # source://yabeda/0.13.1/lib/yabeda.rb#139
    def reset!; end
  end
end

# Minimal set of Rails-specific metrics for using with Yabeda
#
# source://yabeda-rails//lib/yabeda/rails/railtie.rb#8
module Yabeda::Rails
  class << self
    # source://yabeda-rails//lib/yabeda/rails.rb#73
    def config; end

    # source://yabeda-rails//lib/yabeda/rails.rb#19
    def controller_handlers; end

    # Declare metrics and install event handlers for collecting themya
    #
    # source://yabeda-rails//lib/yabeda/rails.rb#29
    def install!; end

    # source://yabeda-rails//lib/yabeda/rails.rb#23
    def on_controller_action(&block); end
  end
end

# yabeda-rails configuration
#
# source://yabeda-rails//lib/yabeda/rails/config.rb#8
class Yabeda::Rails::Config < ::Anyway::Config; end

# ActiveSupport Event with added logic for Yabeda tags formatting
#
# source://yabeda-rails//lib/yabeda/rails/event.rb#6
class Yabeda::Rails::Event < ::ActiveSupport::Notifications::Event
  # source://yabeda-rails//lib/yabeda/rails/event.rb#28
  def db_runtime; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#20
  def duration; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#7
  def labels; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#24
  def view_runtime; end

  private

  # source://yabeda-rails//lib/yabeda/rails/event.rb#43
  def action; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#34
  def controller; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#55
  def format; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#59
  def method; end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#63
  def ms2s(milliseconds); end

  # source://yabeda-rails//lib/yabeda/rails/event.rb#47
  def status; end
end

# source://yabeda-rails//lib/yabeda/rails.rb#13
Yabeda::Rails::LONG_RUNNING_REQUEST_BUCKETS = T.let(T.unsafe(nil), Array)

# source://yabeda-rails//lib/yabeda/rails/railtie.rb#9
class Yabeda::Rails::Railtie < ::Rails::Railtie
  # @return [Boolean]
  #
  # source://yabeda-rails//lib/yabeda/rails/railtie.rb#14
  def puma_server?; end

  # @return [Boolean]
  #
  # source://yabeda-rails//lib/yabeda/rails/railtie.rb#10
  def rails_server?; end

  # @return [Boolean]
  #
  # source://yabeda-rails//lib/yabeda/rails/railtie.rb#18
  def unicorn_server?; end
end
