# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yabeda-puma-plugin` gem.
# Please instead update this file by running `bin/tapioca gem yabeda-puma-plugin`.


# source://yabeda-puma-plugin//lib/yabeda/puma/plugin/version.rb#1
module Yabeda
  class << self
    # source://yabeda/0.13.1/lib/yabeda.rb#34
    def adapters; end

    # source://yabeda/0.13.1/lib/yabeda.rb#85
    def already_configured?; end

    # source://yabeda/0.13.1/lib/yabeda.rb#52
    def collect!; end

    # source://yabeda/0.13.1/lib/yabeda.rb#39
    def collectors; end

    # source://yabeda/0.13.1/lib/yabeda.rb#43
    def config; end

    # source://yabeda/0.13.1/lib/yabeda.rb#80
    def configurators; end

    # source://yabeda/0.13.1/lib/yabeda.rb#93
    def configure!; end

    # source://yabeda/0.13.1/lib/yabeda.rb#85
    def configured?; end

    # source://yabeda/0.13.1/lib/yabeda.rb#116
    def debug!; end

    # source://forwardable/1.3.3/forwardable.rb#231
    def debug?(*args, **_arg1, &block); end

    # source://yabeda/0.13.1/lib/yabeda.rb#63
    def default_tags; end

    # source://yabeda/0.13.1/lib/yabeda.rb#27
    def groups; end

    # source://yabeda/0.13.1/lib/yabeda.rb#22
    def metrics; end

    # source://yabeda/0.13.1/lib/yabeda.rb#69
    def register_adapter(name, instance); end

    # source://yabeda/0.13.1/lib/yabeda.rb#139
    def reset!; end
  end
end

# source://yabeda-puma-plugin//lib/yabeda/puma/plugin/version.rb#2
module Yabeda::Puma; end

# source://yabeda-puma-plugin//lib/yabeda/puma/plugin/version.rb#3
module Yabeda::Puma::Plugin
  class << self
    # Returns the value of attribute control_auth_token.
    #
    # source://yabeda-puma-plugin//lib/yabeda/puma/plugin.rb#8
    def control_auth_token; end

    # Sets the attribute control_auth_token
    #
    # @param value the value to set the attribute control_auth_token to.
    #
    # source://yabeda-puma-plugin//lib/yabeda/puma/plugin.rb#8
    def control_auth_token=(_arg0); end

    # Returns the value of attribute control_url.
    #
    # source://yabeda-puma-plugin//lib/yabeda/puma/plugin.rb#8
    def control_url; end

    # Sets the attribute control_url
    #
    # @param value the value to set the attribute control_url to.
    #
    # source://yabeda-puma-plugin//lib/yabeda/puma/plugin.rb#8
    def control_url=(_arg0); end
  end
end

# source://yabeda-puma-plugin//lib/yabeda/puma/plugin/version.rb#4
Yabeda::Puma::Plugin::VERSION = T.let(T.unsafe(nil), String)
