scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: postgres
    static_configs:
      - targets: ['monitor-db:9187']
  - job_name: nginx
    static_configs:
      - targets: ['web:9991']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['monitor-containers:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['monitor-node:9100']
  - job_name: 'api'
    static_configs:
      - targets: ['api:9394']
  - job_name: 'site'
    static_configs:
      - targets: ['site:9394']
  - job_name: 'loki'
    static_configs:
      - targets: ['monitor-logs:3100']
