scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: postgres
    static_configs:
      - targets: ['metrics-db:9187']
  - job_name: nginx
    static_configs:
      - targets: ['web:9991']
