map "$arg_platform:$http_user_agent" $store_redirect {
    # Allow override via platform arg
    ~*^ios: https://apps.apple.com/app/organize-modern-labor-unions/id6723855445;
    ~*^android: https://play.google.com/store/apps/details?id=app.getorganize.organize;

    # Send Apple devices to the App Store
    ~*iphone|ipod|ipad|macintosh https://apps.apple.com/app/organize-modern-labor-unions/id6723855445;

    # Send all other devices to the Play Store
    default https://play.google.com/store/apps/details?id=app.getorganize.organize;
}
